//
//  Model.swift
//  Splitpay
//
//  Created by Cliff Chan on 2/7/2023.
//


//This model class is generated by chat gpt AI
import Foundation

struct User: Identifiable, Equatable {
    let id: UUID
    let name: String
    var selectedProducts: [CartItem]
    var orders: [Order]
    
    static func ==(lhs: User, rhs: User) -> Bool {
        lhs.id == rhs.id
    }
}

struct Product: Identifiable {
    let id: UUID
    let name: String
    let price: Decimal
    let category: String
}

struct Order: Identifiable {
    let id: UUID
    let products: [Product]
    var totalPrice: Decimal
}

struct CartItem: Identifiable {
    let id: UUID
    let product: Product
    var quantity: Int
}

class Cart: ObservableObject {
    @Published var items: [CartItem] = []
    
    func reset() {
        items.removeAll()
    }
}


// 創建 Product 物件列表
let productData = [
    Product(id: UUID(), name: "北海道產和牛時雨煮", price: Decimal(string: "20") ?? 0 , category: "飯團"),
    Product(id: UUID(), name: "厚切十勝豚", price: Decimal(string: "16") ?? 0, category: "飯團"),
    Product(id: UUID(), name: "北海道產西洋山葵昆布", price: Decimal(string: "16") ?? 0, category: "飯團"),
    Product(id: UUID(), name: "安格斯牛蛋汁壽喜燒", price: Decimal(string: "20") ?? 0, category: "飯團"),
    Product(id: UUID(), name: "本格和風燒牛肉", price: Decimal(string: "16") ?? 0, category: "飯團"),
    Product(id: UUID(), name: "北海道產秋鮭三文魚", price: Decimal(string: "16") ?? 0, category: "飯團"),
    Product(id: UUID(), name: "蒲燒三文魚腩", price: Decimal(string: "16") ?? 0, category: "飯團"),
    Product(id: UUID(), name: "明太子沙律", price: Decimal(string: "16") ?? 0, category: "飯團"),
    Product(id: UUID(), name: "吞拿魚沙律", price: Decimal(string: "16") ?? 0, category: "飯團"),
    Product(id: UUID(), name: "辛口明太子", price: Decimal(string: "16") ?? 0, category: "飯團"),
    Product(id: UUID(), name: "芥末章魚", price: Decimal(string: "16") ?? 0, category: "飯團"),
    Product(id: UUID(), name: "原粒去核梅乾", price: Decimal(string: "16") ?? 0, category: "飯團"),
    Product(id: UUID(), name: "金平牛蒡", price: Decimal(string: "16") ?? 0, category: "飯團")
]

